config/routes.rb
Rails.application.routes.draw do
  root to: 'user_files#index'

  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end
  resources :user_files do
    resources :notes
    resources :receipts
    resources :files, only: [:destroy]
  end

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user_file

  validates_presence_of :text
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]
  before_action :set_user_file

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(user_file_id: params[:user_file_id])
    @note = Note.new
  end

  # GET /notes/1
  # GET /notes/1.json
  def show; end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit; end

  # POST /notes
  # POST /notes.json
  def create
    @note = @user_file.notes.new(note_params)
    respond_to do |format|
      if @note.save
        format.html { redirect_to user_file_notes_path , notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        @notes = Note.where(user_file_id: params[:user_file_id])
        format.html { render :index }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to user_file_notes_path, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to user_file_notes_path, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  def set_user_file
    @user_file = UserFile.find(params[:user_file_id].to_i)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def note_params
    params.require(:note).permit(:text)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div class="row">
  <div class="col s12">
    <%= form_with(model: [@user_file, note], local: true) do |form| %>
        <%= render 'layouts/errors', resource: @note, resource_name: 'Note' %>

        <div class="field">
          <%= form.label :text %>
          <%= form.text_field :text, required: true %>
        </div>


        <div class="actions">
          <%= form.submit nil, class: 'btn-small' %>
        </div>
    <% end %>

  </div>
</div>

app/views/notes/edit.html.erb
<div class="row">
  <h3>Editing Note</h3>
  <div class="col s12 right-align">

    <%= link_to 'Back', user_file_notes_path , class: 'btn-small ' %>

  </div>
</div>

<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<blockquote><h3>Notes</h3></blockquote>
<div class="row">
  <div class="col s12">
    <%= link_to 'back', user_file_path(@user_file), class: 'btn-small right' %>
  </div>
</div>

<div>
  <%= render 'form', note: @note %>
</div>


<%if @user_file.notes.present? %>
    <table class="striped centered">
      <thead>
      <tr>
        <th>Text</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @notes.each do |note| %>
          <tr>
            <td><%= note.text %></td>
            <td><%= note.created_at.strftime('%d %b %Y - %H:%M:%S %P') %></td>
            <td><%= link_to 'Edit', edit_user_file_note_path(@user_file, note), class: 'btn-small' %></td>
            <td><%= link_to 'Destroy', user_file_note_path(@user_file, note), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-small red' %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<%end%>

<br>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>