config/routes.rb
Rails.application.routes.draw do
  root to: 'user_files#index'

  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end
  resources :user_files do
    resources :notes
    resources :receipts
    resources :files, only: [:destroy]
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include Pagy::Backend
  before_action :check_search_query, only: [:results]

  def index;end

  def results
    @search_term = params[:q]
    if params[:attr] == 'name'
      @attr = "concat(first_name, ' ', last_name)"
    else
      @attr = params[:attr]
    end
    @pagy, @user_files = pagy(UserFile.search(@attr, @search_term), items: 10)
  end

  private

  def check_search_query
    if params[:q] == ''
      flash[:alert] = 'No search term was provided!'
      redirect_back fallback_location: root_path
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class="row" style="margin-top: 50px;">
  <div class="col s6 offset-s3">
    <%= form_tag(results_search_index_path, method: "get") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q, nil, placeholder: 'Enter search term', required: true) %>
        <%= label_tag(:attr, "On:") %>
        <%= select_tag(:attr, options_for_select([['Name', 'name'], ['Payment Status', 'payment_status'], %w(Program program)]), class: 'browser-default', style: 'margin-bottom: 15px;') %>
        <%= submit_tag("Search", class: 'btn') %>
    <% end %>
  </div>
</div>

app/views/search/results.html.erb
<div class="row">
  <div class="col s12">
    <% if @pagy.count > 0 %>
      <blockquote><h5><%= pluralize(@user_files.count, 'result')%> found</h5></blockquote>
    <%else%>
      <div id="notfound">
        <div class="notfound">
          <div class="notfound-404">
            <h1>Oops!</h1>
            <h2>No Records Found</h2>
          </div>
          <a href="/search">Search Again</a>
        </div>
      </div>
    <%end%>
  </div>
  <div class="center">
    <%== pagy_nav_materialize(@pagy) if @pagy.pages > 1 %>
  </div>
</div>



<div class="row" style="margin-top: 20px;">

  <% @user_files.each do |user_file| %>
      <%= render 'user_files/card', user_file: user_file %>
  <% end %>
</div>
<div class="center">
  <%== pagy_nav_materialize(@pagy) if @pagy.pages > 1 %>
</div>