config/routes.rb
Rails.application.routes.draw do
  root to: 'user_files#index'

  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end
  resources :user_files do
    resources :notes
    resources :receipts
    resources :files, only: [:destroy]
  end

end

app/models/user_file.rb
class UserFile < ApplicationRecord
  # validation
  validates_presence_of :first_name, :last_name, :address, :ssn, :discount,
                        :placement_date, :payment_status_color, :dob, :fee, :program,
                        :email, :phone_no
  validates_inclusion_of :payment_status_color, in: %w(yellow red purple pink)

  # callback
  before_save :add_payment_status
  before_create :add_due_date 
  before_create :add_balance 
  

  # association
  has_many :notes, dependent: :destroy
  has_many :receipts, dependent: :destroy
  has_many_attached :files

  # scopes
  default_scope { order('created_at desc')}
  scope :search, -> (attr, val){ where(" #{attr} ILIKE ?", "%#{val}%") }

  # payment status color enum to map with the payment status
  enum payment_status_color: { yellow: 'IMMEDIATE F/UP', red:'NON-PAYMENT HOLDS', pink:'CLIENT HOLD REQUEST', purple:'CLOSED FILE' }


  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def add_payment_status
    self.payment_status = UserFile.payment_status_colors[self.payment_status_color.to_sym]
  end

  def add_due_date
    self.due_date = self.placement_date + 1.month if attribute_present?("placement_date")
  end

  def add_balance
    self.balance = self.fee
  end
end

app/controllers/user_files_controller.rb
# frozen_string_literal: true

class UserFilesController < ApplicationController
  include Pagy::Backend
  before_action :set_user_file, only: %i[show edit update destroy]

  # GET /user_files
  # GET /user_files.json
  def index
    @pagy, @user_files = pagy(UserFile.all, items: 6)
  end

  # GET /user_files/1
  # GET /user_files/1.json
  def show; end

  # GET /user_files/new
  def new
    @user_file = UserFile.new
    # @note = @user_file.notes.build
  end

  # GET /user_files/1/edit
  def edit; end

  # POST /user_files
  # POST /user_files.json
  def create
    @user_file = UserFile.new(user_file_params)

    respond_to do |format|
      if @user_file.save
        format.html { redirect_to @user_file, notice: 'User file was successfully created.' }
        format.json { render :show, status: :created, location: @user_file }
      else
        format.html { render :new }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_files/1
  # PATCH/PUT /user_files/1.json
  def update
    respond_to do |format|
      if @user_file.update(user_file_params)
        format.html { redirect_to @user_file, notice: 'User file was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_file }
      else
        format.html { render :edit }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_files/1
  # DELETE /user_files/1.json
  def destroy
    @user_file.destroy
    respond_to do |format|
      format.html { redirect_to user_files_url, notice: 'User file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_file
    @user_file = UserFile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_file_params
    params.require(:user_file).permit(:first_name, :last_name, :fee, :discount, :ssn, :program,
                                      :dob, :address, :placement_date, :payment_status,
                                      :payment_status_color, :email, :phone_no, :balance, :due_date,files: [])
  end
end

app/helpers/user_files_helper.rb
module UserFilesHelper
end

app/views/user_files/_card.html.erb
<div class="col s12 m4">
  <div class="card ">
    <div class="card-content black-text">
      <span style="color: black;" data-badge-caption="<%= user_file.payment_status %>" class="badge <%= user_file.payment_status_color %>"></span>
      <%= link_to user_file.full_name.capitalize , user_file, class: 'card-title' %>
      <ul style="list-style: none">
        <li style="padding: 5px 0px;"><strong>Program </strong> <span class="right"><%= user_file.program.capitalize %></span></li>
        <li class="divider"></li>
        <li style="padding: 5px 0px;"><strong>Fee </strong><span class="right"><%= user_file.fee %></span></li>
        <li class="divider"></li>
        <li style="padding: 5px 0px;"><strong>Balance </strong><span class="right"><%= user_file.balance.present? ? user_file.balance : 'N/A' %></span></li>
        <li class="divider"></li>
        <li style="padding: 5px 0px;"><strong>Due Date </strong><span class="right"><%= user_file.due_date.present? ? user_file.due_date.strftime('%d %b %Y') : 'N/A' %></span></li>
        <li class="divider"></li>
        <li style="padding: 5px 0px;"><strong>Discount </strong><span class="right"><%= user_file.discount %></span></li>
        <li class="divider"></li>
        <li style="padding: 5px 0px;"><strong>Address </strong><span class="right"><%= user_file.address %></span></li>
        <li class="divider"></li>
      </ul>
     </div>
    <div class="card-action">
      <%= link_to 'Notes', user_file_notes_path(user_file) %>
      <%= link_to 'Payments', user_file_receipts_path(user_file) %>
      <%= link_to 'Edit', edit_user_file_path(user_file) %>
      <%= link_to 'Remove', user_file, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>

app/views/user_files/_form.html.erb
<div class="row">
  <div class="col s12">
    <%= form_with(model: user_file, local: true) do |form| %>
        <%= render 'layouts/errors', resource: user_file, resource_name: 'User File' %>


        <div class="field">
          <%= form.label :first_name %>
          <%= form.text_field :first_name %>
        </div>

        <div class="field">
          <%= form.label :last_name %>
          <%= form.text_field :last_name %>
        </div>

        <div class="field">
          <%= form.label :email %>
          <%= form.text_field :email %>
        </div>

        <div class="field">
          <%= form.label :phone_no %>
          <%= form.text_field :phone_no %>
        </div>

        <div class="field">
          <%= form.label :program %>
          <%= form.text_field :program%>
        </div>

        <div class="field">
          <%= form.label :fee %>
          <%= form.number_field :fee %>
        </div>

        <div class="field">
          <%= form.label :discount %>
          <%= form.number_field :discount %>
        </div>

        <div class="field">
          <%= form.label :balance %>
          <%= form.number_field :balance %>
        </div>

        <div class="field">
          <%= form.label :due_date %>
          <%= form.date_field :due_date %>
        </div>

        <div class="field">
          <%= form.label :dob %>
          <%= form.date_field :dob %>
        </div>

        <div class="field">
          <%= form.label :address %>
          <%= form.text_field :address %>
        </div>

        <div class="field">
            <%= form.label :payment_status %>
            <%= form.select(:payment_status_color, [['IMMEDIATE F/UP', 'yellow'], ['CLIENT HOLD REQUEST', 'pink'], ['NON-PAYMENT HOLDS', 'red'], ['CLOSED FILE', 'purple']], {include_blank: true}, class: 'browser-default') %>
        </div>

        <div class="field">
          <%= form.label :ssn %>
          <%= form.text_field :ssn %>
        </div>

        <div class="field">
          <%= form.label :placement_date %>
          <%= form.date_field :placement_date %>
        </div>

        <div class="file-field input-field">
          <div class="btn">
            <span>File</span>
            <%= form.file_field :files, multiple: true %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text" placeholder="Upload one or more files (image and pdf)">
          </div>
        </div>

        <div class="actions">
          <%= form.submit nil, class: 'btn blue lighten-2' %>
        </div>
    <% end %>

  </div>
</div>

app/views/user_files/edit.html.erb
<blockquote><h3>Editing User File</h3></blockquote>

<div class="row">
  <div class="col s12 right-align">

    <%= link_to 'Show', @user_file, class: 'btn-small' %>
    <%= link_to 'Back', user_files_path, class: 'btn-small ' %>

  </div>
</div>

<%= render 'form', user_file: @user_file %>

app/views/user_files/index.html.erb
  <div class="row" >
    <div class="col s12">
      <h3>User Files</h3>
      <%= link_to 'New User File', new_user_file_path, class: 'btn-small waves-light waves-effect blue' %>
    </div>
  </div>

  <div class="center">
    <%== pagy_nav_materialize(@pagy) if @pagy.pages > 1 %>
  </div>

  <div class="row">
    <div class="">
      <% @user_files.each do |user_file| %>
        <%= render 'user_files/card', user_file: user_file %>
      <% end %>
    </div>
  </div>

  <div class="center">
    <%== pagy_nav_materialize(@pagy) if @pagy.pages > 1 %>
  </div>

app/views/user_files/new.html.erb
<blockquote><h3>New User File</h3></blockquote>

<div class="row">
  <div class="col s12 right-align">
    <%= link_to 'Back', user_files_path, class: 'btn-small ' %>
  </div>
</div>

<%= render 'form', user_file: @user_file %>

app/views/user_files/show.html.erb
<div class="row">
  <blockquote><h3>User File</h3></blockquote>
  <div class="col s12 right-align">
    <%= link_to 'Notes', user_file_notes_path(@user_file), class: 'btn-small ' %>
    <%= link_to 'Receipts', user_file_receipts_path(@user_file), class: 'btn-small ' %>
    <%= link_to 'Edit', edit_user_file_path(@user_file), class: 'btn-small ' %>
    <%= link_to 'Back', user_files_path, class: 'btn-small ' %>
  </div>
</div>

<div class="row">
  <div class="col s6 offset-s3">
    <table class="highlight centered responsive-table">
      <tbody>
        <tr>
          <td>Name:</td>
          <td> <%= @user_file.full_name %></td>
        </tr>
        <tr>
          <td>Email:</td>
          <td> <%= @user_file.email %></td>
        </tr>
        <tr>
          <td>Phone Number:</td>
          <td> <%= @user_file.phone_no %></td>
        </tr>
        <tr><td>Program:</td> <td><%= @user_file.program %></td></tr>
        <tr><td>Fee:</td> <td><%= number_to_currency @user_file.fee %></td></tr>
        <tr><td>Discount:</td> <td><%= number_to_currency @user_file.discount %></td></tr>
        <tr><td>Balance:</td> <td><%= @user_file.balance.present? ? number_to_currency(@user_file.balance) : 'N/A' %></td></tr>
        <tr><td>Due Date:</td> <td><%= @user_file.due_date.present? ? @user_file.due_date.strftime('%d %b %Y') : 'N/A' %></td></tr>
        <tr><td>Date of Birth:</td> <td><%= @user_file.dob.strftime('%d %b %Y') %></td></tr>
        <tr> <td>Address: </td><td><%= @user_file.address %></td></tr>
        <tr><td>Social Security:</td> <td><%= @user_file.ssn %></td></tr>
        <tr><td>Placement Date:</td> <td><%= @user_file.placement_date.strftime('%d %b %Y') %></td></tr>
        <tr><td>Payment Satus:</td> <td class=" <%= @user_file.payment_status_color %>-text hover-text" style="background-color: <%= @user_file.payment_status_color %>"><%= @user_file.payment_status %></td></tr>
      </tbody>
    </table>
  </div>
</div>


<div class="row">
  <blockquote><h4>Files</h4></blockquote>
  <div class="col s12">
    <%if @user_file.files.attached? %>
        <table class="striped centered responsive-table">
          <thead>
          <tr>
            <th>Files</th>
            <th colspan="2">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @user_file.files.each do |f|%>
              <% if f.previewable? %>
                  <tr>
                    <td><%= image_tag(f.preview(resize: '100x100')) %></td>
                    <td>
                      <%= link_to('download', rails_blob_path(f, disposition: 'attachment'), target: '_blank', class: 'btn-small ') %>
                      <%= link_to('remove', user_file_file_path(@user_file, f), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-small red' ) %>
                    </td>
                  </tr>
              <%else%>
                  <tr>
                    <td><%= image_tag(f, style: 'width: 100px') %></td>
                    <td>
                      <%= link_to('download', rails_blob_path(f, disposition: 'attachment'), target: '_blank', class: 'btn-small') %>
                      <%= link_to('remove', user_file_file_path(@user_file, f), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-small red' ) %>
                    </td>
                  </tr>

              <%end%>
          <%end%>

          </tbody>
        </table>
    <%else%>
        <div class="card panel blue lighten-3"><span>No Files attached yet!</span></div>
    <%end%>
  </div>
</div>


<div class="row">
  <blockquote><h4>Notes</h4></blockquote>
  <div class="col s12">
    <%if @user_file.notes.present? %>
        <table class="striped centered">
          <thead>
          <tr>
            <th >Text</th>
            <th >Date</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @user_file.notes.each do |note| %>
              <tr>
                <td><%= note.text %></td>
                <td><%= note.created_at.strftime('%d %b %Y - %H:%M:%S %P') %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
    <%else%>
        <div class="card panel blue lighten-3"><span>No Notes created yet!</span></div>
    <%end%>
  </div>
</div>


<div class="row">
  <blockquote><h4>Receipts</h4></blockquote>
  <div class="col s12">
    <%if @user_file.receipts.present? %>
        <table class="striped centered">
          <thead>
          <tr>
            <th>Amount</th>
            <th>Date</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @user_file.receipts.each do |receipt| %>
              <tr>
                <td><%= number_to_currency receipt.amount %></td>
                <td><%= receipt.created_at.strftime('%d %b %Y - %H:%M:%S %P') %></td>
              </tr>
          <% end %>
          </tbody>


        </table>
    <%else%>
        <div class="card panel blue lighten-3"><span>No Receipts created yet!</span></div>
    <%end%>
  </div>
</div>