config/routes.rb
Rails.application.routes.draw do
  root to: 'user_files#index'

  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end
  resources :user_files do
    resources :notes
    resources :receipts
    resources :files, only: [:destroy]
  end

end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user_file

  validates_presence_of :amount
  after_create :deduct_balance
  
  protected

  def deduct_balance
    puts "In deduct balance"
   
    puts "amount: #{self.inspect}"
    # self.user_file.balance = self.user_file.balance - self.amount
    self.user_file.update_attributes(balance: self.user_file.balance - self.amount)
    puts "balance: #{self.user_file.inspect}"
  end 
end

app/controllers/receipts_controller.rb
# frozen_string_literal: true

class ReceiptsController < ApplicationController
  before_action :set_receipt, only: %i[show edit update destroy]
  before_action :set_user_file

  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.where(user_file_id: params[:user_file_id])
    @receipt = Receipt.new
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show; end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit; end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = @user_file.receipts.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to user_file_receipts_path, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        @receipts = Receipt.where(user_file_id: params[:user_file_id])
        format.html { render :index }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to user_file_receipts_path, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to user_file_receipts_path, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_receipt
    @receipt = Receipt.find(params[:id])
  end

  def set_user_file
    @user_file = UserFile.find(params[:user_file_id].to_i)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def receipt_params
    params.require(:receipt).permit(:amount)
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<div class="row">
  <div class="col s12">
    <%= form_with(model: [@user_file, receipt], local: true) do |form| %>
        <%= render 'layouts/errors', resource: @receipt, resource_name: 'Receipt' %>

        <div class="field">
          <%= form.label :amount %>
          <%= form.number_field :amount, required: true %>
        </div>

        <div class="actions">
          <%= form.submit nil, class: 'btn-small' %>
        </div>
    <% end %>

  </div>
</div>

app/views/receipts/edit.html.erb
<div class="row">
  <h3>Editing Receipt</h3>
  <div class="col s12 right-align">

    <%= link_to 'Back', user_file_receipts_path, class: 'btn-small ' %>

  </div>
</div>


<%= render 'form', receipt: @receipt %>

app/views/receipts/index.html.erb
<blockquote class=""><h3>Receipts</h3></blockquote>
<div class="row">
  <div class="col s12">
    <%= link_to 'back', user_file_path(@user_file), class: 'btn-small right' %>
  </div>
</div>

<div>
  <%= render 'form', receipt: @receipt %>
</div>


<%if @user_file.receipts.present? %>

    <table class="striped centered">
      <thead>
      <tr>
        <th>Amount</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @receipts.each do |receipt| %>
          <tr>
            <td><%= number_to_currency receipt.amount %></td>
            <td><%= receipt.created_at.strftime('%d %b %Y - %H:%M:%S %P') %></td>
            <td><%= link_to 'Edit', edit_user_file_receipt_path(@user_file, receipt), class: 'btn-small' %></td>
            <td><%= link_to 'Destroy', user_file_receipt_path(@user_file, receipt), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-small red' %></td>
          </tr>
      <% end %>
      </tbody>


    </table>

<%end%>


<br>

app/views/receipts/new.html.erb
<h1>New Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Back', receipts_path %>